# Generated by Django 4.2.23 on 2025-09-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplicacao", "0004_avaliacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="numero",
            field=models.PositiveIntegerField(verbose_name="Nº"),
        ),
    ]
