# Generated by Django 4.2.23 on 2025-09-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplicacao", "0005_alter_perfil_numero"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avaliacao",
            name="texto_review",
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="review_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
